### ISSUE TITLE
Main

### ISSUE THREAD

**Issue by mariacharadgipse** [mac-ar/Mac_04_MercadoLiebre#2]
- Debe ocupar un 90% del ancho de la pantalla.
- La caja, dentro de la caja general del artículo, que contiene el logo del envío, el precio, el porcentaje de descuento y la descripción del artículo, debe tener un borde superior de 1 píxel, línea sólida y color #ebebeb. También debe tener separado el contenido de sus bordes en 15 píxeles en cada uno de sus lados.
- En el caso mobile la descripción del artículo no se visualizará, pero el resto de los elementos, es decir, el logo del envío, el precio, el porcentaje de descuento permanecen visibles.

**Comment by mac-ar** [comment]
Se realizaron los tres cambios sugeridos. Gracias por las observaciones.
