### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by mariacharadgipse** [mac-ar/Mac_04_MercadoLiebre#3]
-  Cuando el mouse esté por encima del botón de envío del formulario, su color de fondo tiene que cambiar al color #0022AA.
- La estética del formulario es muy diferente de la propuesta, sugerencia para revisar.

**Comment by mac-ar** [comment]
Como explique en la issues de register cambie los colores que a mi me gustan y el color(#0022AA) que proponia el desafio no combina con el formulario asi que puse un color que si combina, por ese motivo el color de transicion del boton queda asi. Creo que mas alla de los colores la idea es entender y aplicar el metodo ":hover" de css para el cambio de color de los elementos. Gracias por tu sugerencia.
