### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by mariacharadgipse** [mac-ar/Mac_04_MercadoLiebre#4]
- La estética del formulario es muy diferente de la propuesta, sugerencia para revisar.

**Comment by mac-ar** [comment]
Hola Maria los colores del formularios no fueron definido en los desafios de la clase 21 que es sobre Formularios, el mockup de muestra es una posible  solucion, como queria hacer algo diferente con lo aprendido de CSS cambie entonces los colores y di un diseño diferente, por tal motivo los colores quedan asi. Gracias por tu sugerencia.
